import { Globe2, Plus } from "lucide-react";
import { saveSeoAction } from "@/app/admin/actions";
import { requireAdmin } from "@/lib/admin/auth";

export const metadata = { title: "SEO Manager" };
type SeoRow = { id:string;route:string;meta_title:string;meta_description:string;canonical_url:string|null;keywords:string[];og_image_url:string|null;robots:string };

function SeoFields({ item }: { item?: SeoRow }) { return <div className="admin-form-grid"><label><span>Route</span><input name="route" defaultValue={item?.route ?? "/"} required /></label><label><span>Robots</span><select name="robots" defaultValue={item?.robots ?? "index,follow"}><option>index,follow</option><option>noindex,nofollow</option><option>noindex,follow</option></select></label><label className="admin-field-full"><span>Meta title</span><input name="meta_title" maxLength={65} defaultValue={item?.meta_title} required /></label><label className="admin-field-full"><span>Meta description</span><textarea name="meta_description" maxLength={165} defaultValue={item?.meta_description} required /></label><label className="admin-field-full"><span>Canonical URL</span><input name="canonical_url" type="url" defaultValue={item?.canonical_url ?? ""} /></label><label className="admin-field-full"><span>Keywords · comma-separated</span><input name="keywords" defaultValue={item?.keywords?.join(", ")} /></label><label className="admin-field-full"><span>Open Graph image URL</span><input name="og_image_url" type="url" defaultValue={item?.og_image_url ?? ""} /></label></div>; }

export default async function SeoPage() { const { supabase } = await requireAdmin("seo.write"); const { data } = await supabase.from("seo_settings").select("*").order("route"); const settings = (data ?? []) as SeoRow[]; return <><div className="admin-page-head"><div><h1>SEO Manager</h1><p>Control search previews, canonical URLs, keywords, indexation, and social sharing images per route.</p></div></div><div className="admin-split"><article className="admin-card"><div className="admin-card-head"><div><h2><Plus size={14} /> Add route metadata</h2><p>Use a path such as /products/vanilla-beans.</p></div></div><form action={saveSeoAction} className="admin-form"><SeoFields /><div className="admin-form-actions"><button className="admin-primary-button">Save metadata</button></div></form></article><section>{settings.length ? settings.map((item) => <details className="admin-list-card" key={item.id}><summary><span className="admin-list-thumb" style={{display:"grid",placeItems:"center"}}><Globe2 size={18} /></span><div><b>{item.meta_title}</b><small>{item.route} · {item.robots}</small></div><span className="admin-badge published">Indexed</span></summary><div className="admin-list-card-body"><form action={saveSeoAction} className="admin-form"><SeoFields item={item} /><div className="admin-form-actions"><button className="admin-primary-button">Update metadata</button></div></form></div></details>) : <div className="admin-card admin-empty"><Globe2 /><h3>No SEO overrides</h3><p>Add metadata for the homepage first.</p></div>}</section></div></>; }
