import { Globe2, Plus } from "lucide-react";
import { saveSeoAction } from "@/app/admin/actions";
import { requireAdmin } from "@/lib/admin/auth";
import { ImageUploadField } from "@/components/admin/ImageUploadField";
import { AdminLivePreview } from "@/components/admin/AdminLivePreview";
import { SubmitButton } from "@/components/admin/SubmitButton";
import { AdminLazyDetails } from "@/components/admin/AdminLazyDetails";

export const metadata = { title: "SEO Manager" };
type SeoRow = { id:string;route:string;meta_title:string;meta_description:string;canonical_url:string|null;keywords:string[];og_image_url:string|null;robots:string };

function SeoFields({ item }: { item?: SeoRow }) { return <div className="admin-form-grid"><label><span>Alamat halaman</span><input name="route" defaultValue={item?.route ?? "/"} required /><small>Contoh: /about atau /products/vanilla-beans</small></label><label><span>Visibilitas Google</span><select name="robots" defaultValue={item?.robots ?? "index,follow"}><option value="index,follow">Boleh tampil di Google</option><option value="noindex,nofollow">Jangan tampil di Google</option><option value="noindex,follow">Tidak diindeks, link boleh diikuti</option></select></label><label className="admin-field-full"><span>Judul Google</span><input name="meta_title" maxLength={65} defaultValue={item?.meta_title} required /><small>Maksimal 65 karakter.</small></label><label className="admin-field-full"><span>Deskripsi Google</span><textarea name="meta_description" maxLength={165} defaultValue={item?.meta_description} required /><small>Maksimal 165 karakter.</small></label><label className="admin-field-full"><span>URL utama (opsional)</span><input name="canonical_url" type="url" defaultValue={item?.canonical_url ?? ""} /></label><label className="admin-field-full"><span>Kata kunci — pisahkan koma</span><input name="keywords" defaultValue={item?.keywords?.join(", ")} /></label><ImageUploadField name="og_image_url" label="Gambar saat link dibagikan" defaultValue={item?.og_image_url ?? ""} folder="seo" help="Ukuran yang disarankan: 1200 × 630 piksel." /></div>; }

export default async function SeoPage() { const { supabase } = await requireAdmin("seo.write"); const { data } = await supabase.from("seo_settings").select("*").order("route"); const settings = (data ?? []) as SeoRow[]; return <><div className="admin-page-head"><div><h1>Pengaturan SEO</h1><p>Atur tampilan halaman di Google dan saat link dibagikan. Preview tersedia langsung di setiap formulir.</p></div></div><div className="admin-split"><article className="admin-card"><div className="admin-card-head"><div><h2><Plus size={14} /> Tambah pengaturan halaman</h2><p>Gunakan alamat seperti /products/vanilla-beans.</p></div></div><form action={saveSeoAction} className="admin-form"><SeoFields /><AdminLivePreview kind="seo" label="Preview Google & media sosial"/><div className="admin-form-actions"><SubmitButton pendingLabel="Menyimpan…">Simpan SEO</SubmitButton></div></form></article><section>{settings.length ? settings.map((item) => <AdminLazyDetails key={item.id} summary={<><span className="admin-list-thumb" style={{display:"grid",placeItems:"center"}}><Globe2 size={18} /></span><div><b>{item.meta_title}</b><small>{item.route} · {item.robots}</small></div><span className="admin-badge published">Aktif</span></>}><div className="admin-list-card-body"><form action={saveSeoAction} className="admin-form"><SeoFields item={item} /><AdminLivePreview kind="seo" label="Preview perubahan"/><div className="admin-form-actions"><SubmitButton pendingLabel="Menyimpan…">Simpan perubahan</SubmitButton></div></form></div></AdminLazyDetails>) : <div className="admin-card admin-empty"><Globe2 /><h3>Belum ada pengaturan SEO</h3><p>Mulai dengan menambahkan pengaturan untuk halaman beranda.</p></div>}</section></div></>; }
