create table if not exists public.quote_requests (
  id bigint generated by default as identity primary key, inquiry_reference text not null unique, created_at timestamptz not null default now(),
  company_name text not null, contact_person text not null, business_email text not null, phone_whatsapp text not null, country text not null,
  company_website text, product_interested text not null, grade text not null, quantity_required text not null, preferred_packaging text not null,
  destination_port text not null, preferred_incoterm text not null, sample_required boolean not null default false,
  additional_requirements text, consent boolean not null, source_page text not null, status text not null default 'new'
  check (status in ('new','contacted','qualified','closed'))
);
create table if not exists public.sample_requests (
  id bigint generated by default as identity primary key, inquiry_reference text not null unique, created_at timestamptz not null default now(),
  company_name text not null, contact_person text not null, business_email text not null, country text not null, product text not null,
  required_grade text not null, intended_use text not null, expected_future_order_volume text not null, shipping_address text not null,
  courier_account text, additional_notes text, consent boolean not null, source_page text not null, status text not null default 'new'
  check (status in ('new','reviewing','approved','declined','dispatched'))
);
alter table public.quote_requests enable row level security;
alter table public.sample_requests enable row level security;
create index if not exists quote_requests_created_at_idx on public.quote_requests (created_at desc);
create index if not exists sample_requests_created_at_idx on public.sample_requests (created_at desc);
