create table if not exists public.quote_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  company_name text not null,
  contact_person text not null,
  email text not null,
  country text not null,
  quantity_required text not null,
  packaging_requirement text,
  incoterm text,
  additional_notes text,
  source_page text not null default '/products/vanilla-beans',
  status text not null default 'new' check (status in ('new','contacted','qualified','closed'))
);

alter table public.quote_requests enable row level security;

create index if not exists quote_requests_created_at_idx on public.quote_requests (created_at desc);
create index if not exists quote_requests_status_idx on public.quote_requests (status);

comment on table public.quote_requests is 'Qualified export quotation inquiries received from the public website. Writes use a server-only service role key.';
